<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ActPurchase.Context.EntituFramework\ActPurchase.Context.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\ActPurchase.Context\ActPurchase.Context.csproj" />
  </ItemGroup>

</Project>
